import type { Metadata } from "next";
import "../globals.css";
import MainHeader from "../../components/main-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden" >
        <div className="mx-[auto] min-[1000px]:w-[900px] max-[1000px]:w-[767px] max-[767px]:w-[90%]">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
